version: 2

sources:
  - name: raw
    database: cba_pipeline
    schema: raw
    tables:
      - name: transactions
        columns:
          - name: transaction_id
            tests:
              - unique
              - not_null
          - name: amount
            tests:
              - not_null
          - name: transaction_type
            tests:
              - not_null
      - name: accounts
        columns:
          - name: account_id
            tests:
              - unique
              - not_null
